# Generated by Django 5.2.12 on 2026-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clubasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='initials',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_code',
            field=models.CharField(max_length=5),
        ),
    ]
